export const SHOW_PROGRESS_BAR_DELAY = 250;

export const COMPLETE_PROGRESS_BAR_DELAY = 1000;

export const LAYOUT_FADE_IN_TIME = 1000;

export const START_TYPING_DELAY =
  SHOW_PROGRESS_BAR_DELAY + COMPLETE_PROGRESS_BAR_DELAY + LAYOUT_FADE_IN_TIME;
